cmd = 'python ./paper_cli_uci.py --jit -mc {model} --precision {precision} --jitter {jitter} --config-dir "/home/artem/code/conjugate-gradient-sparse-gp/cggp/logs/gpr/{dataset}/gpr_matern32_i1000/{seed}" '

# Uniform. Experiment one.
[[exp]]
cmd = '{cmd} {name} -m {max_ip} compute-metrics --logdir "{uid}"'
uid = './{rootdir}/{dataset}/{name}_{model}_m{max_ip}_{precision}_j{jitter}/{seed}'

name = "uniform"
rootdir = "logs/uci"

max_ip = [100, 500, 1000, 2000, 3000, 4000, 5000]

model = ["sgpr"]
dataset = ["elevators", "bike"]
precision = ["fp32", "fp64"]
jitter = ["1e-8", "1e-6", "1e-4", "1e-2", "1e-1"]
seed = [111]


# Oips. Experiment one.
[[exp]]
cmd = '{cmd} {name} --rho {rho} compute-metrics --logdir "{uid}"'
uid = './{rootdir}/{dataset}/{name}_{model}_r{rho}_{precision}_j{jitter}/{seed}'

name = "oips"
rootdir = "logs/uci"

rho = [0.001, 0.005, 0.01, 0.05, 0.1, 0.2, 0.4]

model = ["sgpr"]
dataset = ["elevators", "bike"]
precision = ["fp32", "fp64"]
jitter = ["1e-8", "1e-6", "1e-4", "1e-2", "1e-1"]
seed = [111]


# KMeans. Experiment one.
[[exp]]
cmd = '{cmd} {name} -m {max_ip} compute-metrics --logdir "{uid}"'
uid = './{rootdir}/{dataset}/{name}_{model}_m{max_ip}_{precision}_j{jitter}/{seed}'

name = "kmeans"
rootdir = "logs/uci"

max_ip = [100, 500, 1000, 2000, 3000, 4000, 5000]

model = ["sgpr"]
dataset = ["elevators", "bike"]
precision = ["fp32", "fp64"]
jitter = ["1e-8", "1e-6", "1e-4", "1e-2", "1e-1"]
seed = [111]


[flags]
restart = false
# num_proc = 1
# gpu_indices = ["3"]
num_proc = 3
gpu_indices = ["0", "1", "3"]
