cmd = 'python ./paper_cli.py -l "{uid}" -p {precision} -d {dataset} -s {seed} --jit'

[[exp]]
cmd = '{cmd} -j {jitter} train-adam-covertree -mc {model} -s {resolution} -n {maxiters} -b {batchsize} -tb {test_batchsize} -l {lr} --no-tip'
uid = './{rootdir}/{name}/{dataset}/{model}_{precision}_r{resolution}_i{maxiters}_lr{lr}_b{batchsize}_notip_j{jitter}/{seed}'

name = "adam-covertree"
rootdir = "logs"
dataset = "east_africa"
maxiters = 1000
lr = 0.01
batchsize = 1000
test_batchsize = 3000
model = "sgpr"
resolution = [0.2, 0.1, 0.09, 0.08, 0.07, 0.06, 0.05, 0.04, 0.03, 0.02, 0.01]
# resolution = [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0.0]
jitter = [1e-6, 1e-5, 1e-4]
precision = ["fp32", "fp64"]
seed = [111, 222, 333, 444, 555, 666, 777, 888, 999, 1000, 1111, 2222, 3333, 4444, 5555]


[[exp]]
cmd = '{cmd} train-adam-covertree -mc {model} -s {resolution} -n {maxiters} -b {batchsize} -tb {test_batchsize} -l {lr} --no-tip'
uid = './{rootdir}/{name}/{dataset}/{model}_{precision}_r{resolution}_i{maxiters}_lr{lr}_b{batchsize}_notip/{seed}'

name = "adam-covertree"
rootdir = "logs"
dataset = "east_africa"
maxiters = 1000
lr = 0.01
batchsize = 1000
test_batchsize = 3000
model = "cdgp"
precision = ["fp32", "fp64"]
# resolution = [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0.0]
resolution = [0.2, 0.1, 0.09, 0.08, 0.07, 0.06, 0.05, 0.04, 0.03, 0.02, 0.01]
seed = [111, 222, 333, 444, 555, 666, 777, 888, 999, 1000, 1111, 2222, 3333, 4444, 5555]


# [[exp]]
# cmd = '{cmd} train-adam-covertree -mc {model} -s {resolution} -n {maxiters} -b {batchsize} -tb {test_batchsize} -l {lr} --tip'
# uid = './{rootdir}/{name}/{dataset}/{model}_{precision}_r{resolution}_i{maxiters}_lr{lr}_b{batchsize}_tip/{seed}'

# name = "adam-covertree"
# rootdir = "logs"
# dataset = "east_africa"
# maxiters = 1000
# lr = 0.01
# batchsize = 1000
# test_batchsize = 3000
# model = "sgpr"
# precision = ["fp32", "fp64"]
# resolution = [1.0, 0.9, 0.8, 0.7, 0.6, 0.5]
# seed = [111, 222, 333]


[flags]
restart = false
num_proc = 4
gpu_indices = ["0", "1", "2", "3"]
