cmd = 'python ./paper_cli_predict_mu_var.py -l "{uid}" -p {precision} -d {dataset} -s {seed} --jit'

[[exp]]
cmd = '{cmd} -j {jitter} mean-variance -mc {model} -s {resolution} -b {batchsize} -tb {test_batchsize} --no-tip'
uid = './{rootdir}/{name}/{dataset}/{model}_{precision}_r{resolution}_i{maxiters}_lr{lr}_b{batchsize}_notip_j{jitter}/{seed}'

name = "adam-covertree"
rootdir = "logs"
dataset = "east_africa"
maxiters = 1000
lr = 0.01
batchsize = 1000
test_batchsize = 3000
model = "sgpr"
# resolution = [0.2]
# jitter = [1e-6, 1e-5, 1e-4]
# precision = ["fp32"]
# seed = [111]
resolution = [0.2, 0.1, 0.09, 0.08, 0.07, 0.06, 0.05, 0.04, 0.03, 0.02, 0.01]
jitter = [1e-6, 1e-5, 1e-4]
precision = ["fp32", "fp64"]
seed = [111, 222, 333, 444, 555, 666, 777, 888, 999, 1000, 1111, 2222, 3333, 4444, 5555]


[[exp]]
cmd = '{cmd} mean-variance -mc {model} -s {resolution} -b {batchsize} -tb {test_batchsize} --no-tip'
uid = './{rootdir}/{name}/{dataset}/{model}_{precision}_r{resolution}_i{maxiters}_lr{lr}_b{batchsize}_notip/{seed}'

name = "adam-covertree"
rootdir = "logs"
dataset = "east_africa"
maxiters = 1000
lr = 0.01
batchsize = 1000
test_batchsize = 3000
model = "cdgp"
precision = ["fp32", "fp64"]
resolution = [0.2, 0.1, 0.09, 0.08, 0.07, 0.06, 0.05, 0.04, 0.03, 0.02, 0.01]
seed = [111, 222, 333, 444, 555, 666, 777, 888, 999, 1000, 1111, 2222, 3333, 4444, 5555]


[flags]
restart = true
num_proc = 4
gpu_indices = ["0", "1", "2", "3"]
