cmd = 'python ./paper_cli_geospatial.py -l "{uid}" -mc {model} -p {precision} -d {dataset} -s {seed} --jit'


# OIPS
# [[exp]]
# cmd = '{cmd} -j {jitter} -mc {model} oips --rho {rho} --max-num-ip {max_num_ip} train-adam -n {maxiters} -tb {test_batchsize} -l {lr} --no-tip'
# uid = './{rootdir}/{dataset}/{model}_{precision}_m{max_num_ip}_i{maxiters}_lr{lr}_j{jitter}_notip/{seed}'

# name = "oips"
# rootdir = "logs/oips"
# dataset = "elevators"
# maxiters = 1000
# lr = 0.01
# test_batchsize = 5000
# rho = [0.1, 0.5]
# max_num_ip = 5000
# model = "sgpr"
# jitter = [0.0, 1e-8, 1e-6, 1e-4, 1e-2, 1e-1]
# precision = ["fp64", "fp32"]
# seed = [111]


# Covertree CDGP
[[exp]]
cmd = '{cmd} covertree -s {resolution} train-adam -n {maxiters} -b {batchsize} -tb {test_batchsize} -l {lr} --no-tip'
uid = './{rootdir}/{name}/{dataset}/{model}_{precision}_s{resolution}_i{maxiters}_lr{lr}_b{batchsize}_notip/{seed}'

name = "geospatial_covertree"
rootdir = "logs"
dataset = "east_africa"
maxiters = 1000
lr = 0.01
batchsize = 1000
test_batchsize = 1000
model = "cdgp"
precision = ["fp32", "fp64"]
# resolution = [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0.0]
# resolution = [0.2, 0.1, 0.09, 0.08, 0.07, 0.06, 0.05, 0.04, 0.03, 0.02, 0.01]
resolution = [0.02, 0.03, 0.05, 0.06, 0.08, 0.09, 0.1, 0.2, 0.3, 0.4]
seed = [111, 222, 333, 444, 555, 666, 777, 888, 999, 1000]

# Covertree SGPR
[[exp]]
cmd = '{cmd} -j {jitter} covertree -s {resolution} train-adam -n {maxiters} -b {batchsize} -tb {test_batchsize} -l {lr} --no-tip'
uid = './{rootdir}/{name}/{dataset}/{model}_{precision}_j{jitter}_s{resolution}_i{maxiters}_lr{lr}_b{batchsize}_notip/{seed}'

name = "geospatial_covertree"
rootdir = "logs"
dataset = "east_africa"
maxiters = 1000
lr = 0.01
batchsize = 1000
test_batchsize = 1000
model = "sgpr"
precision = ["fp32", "fp64"]
jitter = [1e-8, 1e-6, 1e-4, 1e-2]
# resolution = [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0.0]
# resolution = [0.2, 0.1, 0.09, 0.08, 0.07, 0.06, 0.05, 0.04, 0.03, 0.02, 0.01]
resolution = [0.02, 0.03, 0.05, 0.06, 0.08, 0.09, 0.1, 0.2, 0.3, 0.4]
# seed = [111, 222, 333, 444, 555, 666, 777, 888, 999, 1000, 1111, 2222, 3333, 4444, 5555]
# seed = [111, 222]
seed = [111, 222, 333, 444, 555, 666, 777, 888, 999, 1000]


[flags]
restart = false
num_proc = 4
gpu_indices = ["0", "1", "2", "3"]
