cmd = 'python ./paper_cli_uci.py --jit -mc {model} --precision {precision} --jitter {jitter} --config-dir /home/artem/code/conjugate-gradient-sparse-gp/cggp/logs/gpr/{dataset}/gpr_matern32_i*/{seed} '


# Grad inducing points. SGPR
[[exp]]
cmd = '{cmd} {selection} -m {max_ip} -n {num_iterations} compute-metrics --logdir "{uid}"'
uid = './{rootdir}/{dataset}/{selection}_{model}_m{max_ip}_n{num_iterations}_{precision}_j{jitter}/{seed}'

selection = "grad_ip"
rootdir = "logs/uci"

max_ip = [100, 500, 1000, 2000, 3000, 4000, 5000]

model = ["sgpr"]
dataset = ["east_africa", "power", "naval"]
precision = ["fp32", "fp64"]
jitter = ["1e-8", "1e-6", "1e-4", "1e-2", "1e-1"]
seed = [111, 222, 333, 444, 555, 666, 777, 888, 999]
num_iterations = 1000


# Grad inducing points. CDGP
[[exp]]
cmd = '{cmd} {selection} -m {max_ip} -n {num_iterations} compute-metrics --logdir "{uid}"'
uid = './{rootdir}/{dataset}/{selection}_{model}_m{max_ip}_n{num_iterations}_{precision}_j{jitter}/{seed}'

selection = "grad_ip"
rootdir = "logs/uci"

max_ip = [100, 500, 1000, 2000, 3000, 4000, 5000]

model = ["cdgp"]
dataset = ["east_africa", "power", "naval"]
precision = ["fp32", "fp64"]
jitter = ["1e-6"]
seed = [111, 222, 333, 444, 555, 666, 777, 888, 999]
num_iterations = 1000


[flags]
restart = false
# num_proc = 1
# gpu_indices = ["0"]
num_proc = 4
gpu_indices = ["0", "1", "2", "3"]
